<%@ Page Title="Learn More About HINTS | HINTS" Language="VB" MasterPageFile="~/hintsmain.master" AutoEventWireup="false" CodeFile="learn-more-about-hints.aspx.vb" Inherits="aboutfolder_learn_more_about_hints" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <meta name="Title" content="Learn More About HINTS | HINTS" />
    <meta name="Description" content="The HINTS data collection program was created to monitor changes in the rapidly evolving field of health communication." />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">

    <div class="container col-lg-12 col-xl-7 col custom-wrapper">
        <section>
            <div class="row">
                <div class="col-md-12">

                    <h1>About HINTS</h1>

                    <div id="about_image">
                        <a target="_blank" href="/docs/HINTS_Factsheet_2026.pdf">HINTS Fact Sheet<br />
                            <img src="/_images/Hints_Factsheet_2026.png" alt="Image of HINTS Fact Sheet" /></a>
                    </div>

                    <p>
                        <a name="what"></a><strong>What HINTS Does</strong>
                    </p>
                    <p>
                        The Health Information National Trends Survey (HINTS) routinely collects nationally representative data about Americans’ health- and cancer-related knowledge, attitudes, and behaviors; use of information technology for health-related purposes; and health information-seeking preferences and needs. Most data are made publicly available for use by researchers, health advocates, and program planners. 
                    </p>

                    <p>
                        <a name="how"></a><strong>How HINTS Data Are Used</strong>
                    </p>
                    <p>
                        The HINTS program was created to monitor changes in the rapidly evolving field of health communication, with the goal of informing efforts that may help reduce the burden of cancer. Researchers can use HINTS data to monitor changes in the health communication environment, study the impact of communication on key processes affecting the health of American adults, and refine and develop theories of health communication. Program planners can use the insights generated by HINTS data to create more effective health communication strategies for different populations. 
                    </p>



                    <%--                    <p><a name="presentations"></a><strong>NCI Presentations</strong></p>
                    <p>
                        The following presentations were presented to researchers at the National Cancer
            Institute. They are provided here as background to the survey and the analytic methodologies
            appropriate for nationally weighted probability samples.
                    </p>
                    <ul>
                        <li>HINTS Presentation to NCI Director, presented 12-18-2003 <a href="/docs/HINTS-Briefing-12-18-03.pdf" target="_blank">PDF</a> (2.3 MB)</li>
                        <li>Analyzing Weighted Survey Data, presented 2-9-2004 <a href="/docs/Using-Survey-Weights12-13-05.pdf" target="_blank">PDF</a> (83 KB)</li>
                        <li>Webinar: HINTS: Progress, Plans and Potentials, presented 6-27-2007
                <a href="/docs/webinar_6-27-07.wmv" target="_blank">WMV</a> (7.2
                MB)</li>
                    </ul>--%>

                    <p><a name="sponsors"></a><strong>HINTS Sponsors</strong></p>
                    <p>
                        HINTS was developed by the <a href="https://cancercontrol.cancer.gov/brp/hcirb/" target="_blank">Health Communication and Informatics Research Branch (HCIRB)</a> of the National Cancer Institute's <a href="http://cancercontrol.cancer.gov/" target="_blank">Division of Cancer Control and Population Sciences (DCCPS)</a> in response to the National Cancer Institute's Extraordinary Opportunity in Cancer Communications. To learn more about communication and informatics research at NCI, please visit the <a href="https://cancercontrol.cancer.gov/brp/hcirb/" target="_blank">HCIRB</a> and <a href="http://cancercontrol.cancer.gov/" target="_blank">DCCPS Websites</a>. Some HINTS administrations have been co-sponsored by other federal agencies, including the Food and Drug Administration (FDA) and Assistant Secretary for Technology Policy/Office of the National Coordinator for Health Information Technology (ASTP/ONC).
                    </p>

                    <p><a name="survey"></a><strong>Using HINTS Items in Your Survey</strong></p>
                    <p>Are you a researcher interested in conducting a HINTS-like health communication survey in your community or country? If so, you are welcome to use HINTS items from our publicly available <a href="/data/survey-instruments.aspx" target="_blank">survey instruments</a> for your data collection effort. The NCI HINTS program encourages and supports any opportunity to standardize measures and promote data harmonization for health communication research. However, please do not duplicate any NCI HINTS instruments in their entirety as part of your data collection efforts. Additionally, please refrain from using either the HINTS name (in full or in acronym form) or the HINTS logo for projects unaffiliated with NCI. The name “Health Information National Trends Survey”, the acronym “HINTS”, and the HINTS logo are registered trademarks with the United States Patent and Trademark Office. </p>
                    <p>Additionally, the NCI HINTS management team can provide limited consultation on external data collection efforts related to health communication. If you are interested in discussing your data collection effort with the HINTS management team, please contact us directly at <a href="mailto:NCIhints@mail.nih.gov">NCIhints@mail.nih.gov</a>.</p>
                    <p style="text-align: center;"><strong>For additional information about the HINTS program, please use our <a href="/about-hints/contact-us.aspx" target="_blank">contact form</a> or email <a href="mailto:NCIhints@mail.nih.gov">NCIhints@mail.nih.gov</a>.</strong></p>
                </div>
            </div>
        </section>
    </div>
</asp:Content>

